"""make user, token, user_login models

Revision ID: 892ef653432e
Revises: 
Create Date: 2025-08-19 19:13:52.231618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '892ef653432e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('access_token', sa.String(length=255), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('expires_in', sa.DateTime(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('access_token')
                    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('password', sa.String(length=255), nullable=False),
                    sa.Column('gender', sa.Enum('male', 'female', name='gender_enum'), nullable=True),
                    sa.Column('date_of_birth', sa.Date(), nullable=True),
                    sa.Column('phone', sa.String(length=20), nullable=True),
                    sa.Column('address', sa.String(length=255), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('logs',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('level', sa.String(length=50), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('action', sa.String(), nullable=False),
                    sa.Column('object_type', sa.String(), nullable=False),
                    sa.Column('object_id', sa.Integer(), nullable=False),
                    sa.Column('ip_address', sa.String(length=45), nullable=True),
                    sa.Column('user_agent', sa.String(), nullable=True),
                    sa.Column('message', sa.Text(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user_logins',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('ip_address', sa.String(), nullable=True),
                    sa.Column('user_agent', sa.String(), nullable=True),
                    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_user_logins_id'), 'user_logins', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_logins_id'), table_name='user_logins')
    op.drop_table('user_logins')
    op.drop_table('logs')
    op.drop_table('users')
    op.drop_table('tokens')
    # ### end Alembic commands ###
