"""table of user login

Revision ID: dc01b5d9cfa0
Revises: e9abe26add4f
Create Date: 2025-08-16 21:02:04.670911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc01b5d9cfa0'
down_revision: Union[str, None] = 'e9abe26add4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user_logins',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('ip_address', sa.String(), nullable=True),
        sa.Column('user_agent', sa.String(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_logins_id'), 'user_logins', ['id'], unique=False)
    op.alter_column(
        'users', 'gender',
        existing_type=postgresql.ENUM('male', 'female', name='gender_enum'),
        type_=sa.Enum('male', 'female', name='gender_enum'),
        existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users', 'gender',
        existing_type=sa.Enum('male', 'female', name='gender_enum'),
        type_=postgresql.ENUM('male', 'female', name='gender_enum'),
        existing_nullable=True)
    op.drop_index(op.f('ix_user_logins_id'), table_name='user_logins')
    op.drop_table('user_logins')
    # ### end Alembic commands ###
